
pool:
  vmImage: 'Ubuntu-16.04'    

trigger:
  branches:
    include:
    - master # test trigger      

variables:
  imageName: 'personal-quiz-image:$(build.buildId)'

steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
    verbose: false
  - task: Npm@1
    displayName: 'install angular cli'
    inputs:
      command: custom
      verbose: false
      customCommand: 'install @angular/cli -g'
  - script: npm run build
    displayName: 'run build'
  - script: docker build -f Dockerfile -t $(imageName) .
    displayName: 'docker build'

      