
trigger:
  branches:
    include:
    - master # test trigger      

variables:
  imageName: 'personal-quiz-image:$(build.buildId)'

steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs: 
      command: ci
      verbose: false
  - script: npm run build
    displayName: 'run build'
  - script: |
      docker build -f Dockerfile -t $(imageName) .
      docker login -u danielclain -p $(dockerPassword)
      docker push danielclain/$(imageName)
    displayName: 'docker build'

      