
pool:
  vmImage: 'Ubuntu-16.04'    

trigger:
  branches:
    include:
    - master # test trigger      

variables:
  imageName: 'personal-quiz-image:$(build.buildId)'

steps:
  - script: echo hello world
  - script: npm run build
  - script: docker build -f Dockerfile -t $(imageName) .
    displayName: 'docker build'

      