
trigger:
  branches:
    include:
    - master

variables:
  envName: personal-quiz-demo
  imgName: $(envName)-image

steps:
- task: ShellScript@2
  displayName: 'Environment Handler'
  inputs:
    scriptPath: ./azure-pipeline/environment-handler.sh
    args: $(envName)
    failOnStandardError: true
- task: Npm@1
  displayName: 'npm install'
  condition: always()
  inputs: 
    command: custom
    customCommand: ci
    verbose: false
- script: ng build --configuration=demo
  displayName: 'run demo build'
- script: |
    docker build -t danielclain/$(imgName) ./azure-pipeline
    docker login -u danielclain -p $(dockerPassword)
    docker push danielclain/$(imgName)
  displayName: 'docker build'

      