
trigger:
  branches:
    include:
    - master

variables:
  webappName: personal-quiz-demo
  imgName: $(webappName)-image

steps:
- task: ShellScript@2
  displayName: 'Environment Handler'
  inputs:
    scriptPath: ./azure-pipeline/environment-handler.sh
    args: $(webappName)
    failOnStandardError: true
- task: Npm@1
  displayName: 'npm install'
  condition: always()
  inputs: 
    command: custom
    customCommand: ci
    verbose: false
- script: npm run build-demo
  displayName: 'run demo build'
- script: |
    docker build -t danielclain/$(imgName):latest ./azure-pipeline
    docker login -u danielclain -p $(dockerPassword)
    docker push danielclain/$(imgName):latest
  displayName: 'docker build'

      